name: Scheduled NDK 16 CI build

on:
  workflow_dispatch:
  schedule:
  - cron: '31 9 2 * *'

jobs:
  trigger-main-workflow:
    uses: cloudonix/android-ndk-cmakego/.github/workflows/podman-image.yml
    with:
      override_ref: ndk16
